.github/scripts/get-path-prefix.js
This pull request (PR) adds a script that's needed to deploy the website.
- ...
- ...
=> Add missing script

src/pages/admin-ui-sdk/app-registration.md, src/pages/admin-ui-sdk/troubleshooting.md
This pull request (PR) adds a troubleshooting tip and a updates the description at the top of the Registration topic.
- ...
- ...
=> Add troubleshooting tip and feedback

src/pages/amazon-sales-channel/index.md
This pull request (PR) adds some feedback that I received via Slack during the review cycle for #24.
- ...
- ...
=> Review comments

src/pages/amazon-sales-channel/installation.md
This pull request (PR) fixes an incomplete code example.
- ...
- ...
=> Fix xml code sample

src/pages/amazon-sales-channel/index.md, src/pages/amazon-sales-channel/installation.md
This pull request (PR) adds links to the ASC repo.
- ...
- ...
=> Add links to repo

src/pages/amazon-sales-channel/index.md
This pull request (PR) adds a link to the ASC app repo.
- ...
- ...
=> Add link to ASC repo

src/pages/amazon-sales-channel/installation.md, src/pages/amazon-sales-channel/prerequisites.md
This pull request (PR) updates the Prerequisites page so that it is more consistent with the Eventing documentation. It eliminates workspace navigation commands, because it is out of scope here.
- ...
- ...
=> Update ASC app prereqs

src/pages/admin-ui-sdk/installation.md
This pull request (PR) adds a section that points to setting up Adobe IMS for Commerce.
- ...
- ...
=> Add Adobe IMS section

src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md
This pull request (PR) adds a code sample and a link to the App Builder New Relic logging docs.
- ...
- ...
=> Add runtime actions and New Relic sections

src/pages/admin-ui-sdk/app-registration.md, src/pages/admin-ui-sdk/configuration.md, src/pages/admin-ui-sdk/extension-points/index.md, src/pages/admin-ui-sdk/extension-points/menu.md, src/pages/admin-ui-sdk/extension-points/page.md, src/pages/admin-ui-sdk/extension-points/product.md, src/pages/admin-ui-sdk/index.md, src/pages/admin-ui-sdk/installation.md, src/pages/admin-ui-sdk/release-notes.md, src/pages/admin-ui-sdk/troubleshooting.md, src/pages/amazon-sales-channel/best-practices/credentials.md, src/pages/amazon-sales-channel/best-practices/database-storage.md, src/pages/amazon-sales-channel/best-practices/index.md, src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md, src/pages/amazon-sales-channel/index.md, src/pages/amazon-sales-channel/installation.md, src/pages/amazon-sales-channel/prerequisites.md, src/pages/amazon-sales-channel/release-notes.md, src/pages/app-development/index.md, src/pages/events/commands.md, src/pages/events/conditional-events.md, src/pages/events/configure-commerce.md, src/pages/events/custom-event-fields.md, src/pages/events/index.md, src/pages/events/installation.md, src/pages/events/module-development.md, src/pages/events/project-setup.md, src/pages/events/release-notes.md, src/pages/index.md
This pull request (PR) adds missing metadata (aka "frontmatter")  to all topics in this repo. In particular, it adds `keywords` that can be used to enhance site search results.
See COMDOX-345 for details.
=> COMDOX-345: Add missing metadata

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for Admin UI SDK 1.1.1.
- ...
- ...
=> Add Admin UI SDK 1.1.1 release notes

src/pages/events/release-notes.md
This pull request (PR) fixes a copy and paste error
- ...
- ...
=> Fix the release date of Events 1.3.0

src/data/navigation/header.js, src/data/navigation/sections/index.js, src/data/navigation/sections/webhooks.js, src/pages/webhooks/commands.md, src/pages/webhooks/index.md, src/pages/webhooks/installation.md, src/pages/webhooks/release-notes.md
This pull request (PR) adds stub files and navigation for webhooks.
- ...
- ...
=> Add Webhooks stub files/nav

src/pages/webhooks/commands.md, src/pages/webhooks/installation.md
This pull request (PR) will add information about webhooks CLI commands and installation steps
- ...
- ...
=> Add examples for CLI commands and installation steps

src/pages/webhooks/index.md
This pull request (PR) will add information about webhooks configuration
- ...
- ...
=> Add examples of webhooks and xml schema description

src/pages/webhooks/index.md
This pull request (PR) documents changes being made in https://github.com/magento-commerce/commerce-webhooks/pull/39
- ...
- ...
=> Update context fields documentation

src/pages/webhooks/use-cases.md
This pull request (PR) adds the webhooks use cases topic
- ...
- ...
=> Add use cases topic

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for Admin UI SDK v1.1.1
- ...
- ...
=> Release notes for SDK 1.1.1

src/pages/webhooks/installation.md
Reverts AdobeDocs/commerce-extensibility#86
=> Revert "Instruction on how to install ece-tools from git"

src/pages/admin-ui-sdk/configuration.md, src/pages/admin-ui-sdk/extension-points/index.md, src/pages/admin-ui-sdk/extension-points/order.md, src/pages/admin-ui-sdk/extension-points/product.md
This pull request (PR) adds information about shared contexts
- ...
- ...
=> Add shared context info

src/pages/events/installation.md
This pull request (PR) will update steps for eventing installation, some steps is not required for the cloud installation
- https://developer.adobe.com/commerce/extensibility/events/installation/
- ...
=> Update installation steps for commerce eventing

src/pages/index.md
This pull request (PR) fixes a typo on the landing page.
- https://developer.adobe.com/commerce/extensibility/
=> Fix typo on landing page

src/pages/events/conditional-events.md, src/pages/webhooks/conditional-webhooks.md
This pull request (PR) will add information about conditional webhooks
https://jira.corp.adobe.com/browse/CEXT-2542
- new page
=> CEXT-2542: Document the conditional webhooks

src/pages/events/installation.md, src/pages/events/release-notes.md
This pull request (PR) creates release notes for Eventing 1.4.0 and updates the install/upgrade instructions.
- ...
- ...
=> Eventing 1.4.0 release notes

src/pages/webhooks/installation.md, src/pages/webhooks/release-notes.md
This pull request (PR) creates release notes and upgrade information for the 1.1.0 release of Webhooks.
- ...
- ...
=> Webhooks 1.1 release notes and update

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for version 1.3.0 of the Admin UI SDK.
- ...
- ...
=> SDK 1.3.0 release notes

src/pages/events/installation.md
This pull request (PR) updates the eventing update procedure to include the setup:di:compile command.
- ...
- ...
=> Add step to eventing update procedure

src/pages/admin-ui-sdk/extension-points/order/mass-action.md, src/pages/admin-ui-sdk/extension-points/product/mass-action.md, src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) creates the release notes for Admin UI SDK 1.3.1.
- ...
- ...
=> SDK 1.3.1 release notes

src/pages/webhooks/release-notes.md
This pull request (PR) adds release notes for v1.2.0.
- ...
- ...
=> Webhooks 1.2.0 release notes

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) updates the Admin UI SDK release notes for v1.3.2.
- ...
- ...
=> SDK 1.3.2 release notes

src/pages/app-development/starter-kit/actions-overview.md, src/pages/app-development/starter-kit/index.md
merging dev branches. please ignore.
=> index review

src/pages/webhooks/index.md
This pull request (PR) provides an update to the overview page for webhooks needed now that data-modifying webhooks are supported.
- https://developer.adobe.com/commerce/extensibility/webhooks/
- ...
=> Data-modifying webhook update for overview page

src/pages/webhooks/commands.md
This pull request (PR) ...
- https://developer.adobe.com/commerce/extensibility/webhooks/commands/#emulate-webhook-execution
- ...
=> Fix typo in webhooks:dev:run command description

src/pages/app-development/starter-kit/create-data-flow.md, src/pages/app-development/starter-kit/customers.md, src/pages/app-development/starter-kit/orders.md, src/pages/app-development/starter-kit/products.md, src/pages/app-development/starter-kit/shipments.md, src/pages/app-development/starter-kit/stock.md, src/pages/app-development/starter-kit/webhooks.md
This PR adds data flow documentation to the existing PR #184
=> data flows

src/data/navigation/header.js
This pull request (PR) adds Mesh to the top navigation
- ...
- ...
=> Add topnav link to Mesh

src/_includes/starter-kit-beta.md, src/data/navigation/sections/starter-kit.js, src/pages/starter-kit/create-integration.md, src/pages/starter-kit/index.md
This pull request (PR) adds content to the index page and cleans up various loose ends.
- ...
- ...
=> Final prep for Starter Kit beta docs

src/data/navigation/header.js, src/data/navigation/sections/starter-kit.js, src/pages/app-development/learning-path.md
This pull request (PR) creates hard links to the EDS-served Starter Kit index page.
- ...
- ...
=> Attempts to fix nav

src/data/navigation/header.js, src/data/navigation/sections/starter-kit.js
Reverts previous nav change for testing.
=> revert nav change

src/_includes/integration.md, src/_includes/starter-kit-beta.md, src/pages/starter-kit/best-practices.md, src/pages/starter-kit/contact-us.md, src/pages/starter-kit/create-integration.md, src/pages/starter-kit/customers.md, src/pages/starter-kit/data-flows.md, src/pages/starter-kit/developer-tools.md, src/pages/starter-kit/events.md, src/pages/starter-kit/index.md, src/pages/starter-kit/orders.md, src/pages/starter-kit/products.md, src/pages/starter-kit/receive-data.md, src/pages/starter-kit/shipments.md, src/pages/starter-kit/stock.md, src/pages/starter-kit/structure.md, src/pages/starter-kit/use-cases.md, src/pages/starter-kit/webhooks.md
This pull request (PR) updates the product name to Adobe Commerce Integration Starter Kit.
- ...
- ...
=> Update product name

src/data/navigation/sections/starter-kit.js
This pull request (PR) updates the left navigation
- ...
- ...
=> Update left nav

src/pages/admin-ui-sdk/configuration.md
This pull request (PR) updates Admin UI SDK configuration and testing page with correct URLs to new repositories and simplified local server configurations.
- ...
- ...
=> Update Admin UI SDK configuration and testing page

src/data/navigation/sections/starter-kit.js, src/pages/starter-kit/ms-finance.md
This pull request (PR) adds the MS Finance topic to the left nav and links to its corresponding page on the Adobe Exchange.
- ...
- ...
=> Updares to MS Finance topic

src/pages/events/release-notes.md
This pull request (PR) adds release notes for commerce eventing modules.
https://jira.corp.adobe.com/browse/CEXT-3321
- ...
=> CEXT-3321: Release commerce eventing service and eventing modules

src/data/navigation/sections/admin-ui-sdk.js, src/pages/admin-ui-sdk/extension-points/customer/mass-action.md, src/pages/admin-ui-sdk/extension-points/order/mass-action.md, src/pages/admin-ui-sdk/extension-points/product/mass-action.md
This pull request (PR) fixes a pair of relative links that don't resolve for some reason.
- ...
- ...
=> Fix broken relative links

src/pages/starter-kit/create-integration.md
This PR removes an inconsistency in the scripts/onboarding/config/starter-kit-registrations.json sample code used in the documentation.
- https://developer.adobe.com/commerce/extensibility/starter-kit/create-integration/
- https://github.com/adobe/commerce-integration-starter-kit/pull/13
=> remove shipments from starter-kit-registrations.json code sample

src/pages/events/release-notes.md
This pull request (PR) adds information about changes in the latest release.
- ...
=> CEXT-3451: Release commerce eventing modules

src/pages/events/release-notes.md
This pull request (PR) adds information about changes in the latest release.
https://jira.corp.adobe.com/browse/CEXT-3483
- ...
=> CEXT-3483: Release commerce eventing modules 1.8.2

src/pages/app-development/examples.md, src/pages/starter-kit/events.md, src/pages/starter-kit/receive-data.md, src/pages/starter-kit/webhooks.md
This pull request (PR) sets matching languages in Code and CodeBlock components.
- https://commerce-docs.github.io/commerce-extensibility/starter-kit/webhooks/
- https://commerce-docs.github.io/commerce-extensibility/starter-kit/events/
- https://commerce-docs.github.io/commerce-extensibility/starter-kit/receive-data/
=> Set matching languages in CodeBlock

src/pages/admin-ui-sdk/app-registration.md, src/pages/admin-ui-sdk/extension-points/banner-notification.md, src/pages/admin-ui-sdk/extension-points/customer/grid-columns.md, src/pages/admin-ui-sdk/extension-points/customer/mass-action.md, src/pages/admin-ui-sdk/extension-points/index.md, src/pages/admin-ui-sdk/extension-points/menu.md, src/pages/admin-ui-sdk/extension-points/order/custom-fees.md, src/pages/admin-ui-sdk/extension-points/order/grid-columns.md, src/pages/admin-ui-sdk/extension-points/order/mass-action.md, src/pages/admin-ui-sdk/extension-points/order/view-button.md, src/pages/admin-ui-sdk/extension-points/page.md, src/pages/admin-ui-sdk/extension-points/product/grid-columns.md, src/pages/admin-ui-sdk/extension-points/product/mass-action.md, src/pages/admin-ui-sdk/installation.md, src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) updates documentation for Admin UI SDK 2.0 release
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/app-registration/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/banner-notification/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/customer/grid-columns/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/customer/mass-action/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/menu/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/order/custom-fees/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/order/grid-columns/
- …
=> Admin UI SDK 2.0 release, documentation update

src/pages/events/convert-field-values.md, src/pages/events/custom-event-fields.md
This pull request (PR) updates the copyright in code samples.
- https://developer.adobe.com/commerce/extensibility/events/convert-field-values/
- https://developer.adobe.com/commerce/extensibility/events/custom-event-fields/
=> Update the copyright in code samples

src/pages/events/convert-field-values.md, src/pages/events/custom-event-fields.md
This pull request (PR) updates the copyright header in code samples.
=> Update copyright in code samples

src/pages/webhooks/signature-verification.md
This pull request (PR) adds additional documentation on how to use webhooks signature verification.
https://jira.corp.adobe.com/browse/CEXT-3897
- https://developer.adobe.com/commerce/extensibility/webhooks/signature-verification/
- ...
=> CEXT-3897: Documentation update for webhooks signature verification

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) ...
- ...
- ...
=> Add Admin UI SDK 2.1.1 release notes

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for 1.4.1 admin UI SDK release
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/release-notes/
- ...
=> CEXT-4013: Release admin ui sdk 1.4.1 with the fix for di compilation

src/pages/admin-ui-sdk/configuration.md
This pull request (PR) clarifies Admin UI SDK sandbox option and eligible workspace
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/configuration/
- ...
=> Clarify Admin UI SDK sandbox option and eligible workspace

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for Admin UI SDK 2.2.0
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/release-notes/
- ...
=> Add release notes for Admin UI SDK 2.2.0

src/pages/admin-ui-sdk/extension-points/index.md
This pull request (PR) adds a missing line to the `sharedContext` example.
- ...
- ...
=> Update sharedContext example

src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) ...
- ...
- ...
=> Add instance field

src/pages/admin-ui-sdk/installation.md
This pull request (PR) updates the SDK install docs to mention it's installed automatically on 2.4.8.
- ...
- ...
=> Update Admin UI SDK install topic

src/pages/events/release-notes.md
This pull request (PR) changes the date of the most recent eventing release.
- ...
- ...
=> Change the date in the eventing release notes

src/pages/starter-kit/checkout/connect.md
This pull request (PR) ...
- ...
- ...
=> Add COMMERCE_BASE_URL examples

src/pages/starter-kit/checkout/eds.md, src/pages/starter-kit/checkout/tax-reference.md, src/pages/starter-kit/tax/index.md
* Reference EDS Storefront docs for payment methods integration
* Add tips for graphql full tax breakdown
- ...
- ...
=> CEXT-4623: update eds docs

src/pages/starter-kit/checkout/payment-use-cases.md
This PR standardizes webhook formatting to make it easier to read.
=> Webhook formatting

src/pages/webhooks/use-cases/check-gift-card-balance.md, src/pages/webhooks/use-cases/code-samples/check-gift-card-balance-admin.md, src/pages/webhooks/use-cases/code-samples/customer-address-mod-admin.md, src/pages/webhooks/use-cases/code-samples/customer-address-validation-admin.md, src/pages/webhooks/use-cases/code-samples/discount-code-validation-admin.md, src/pages/webhooks/use-cases/code-samples/gift-card-validation-admin.md, src/pages/webhooks/use-cases/code-samples/order-placement-validation-admin.md, src/pages/webhooks/use-cases/code-samples/product-generate-content-admin.md, src/pages/webhooks/use-cases/code-samples/product-price-update-admin.md, src/pages/webhooks/use-cases/code-samples/product-stock-validation-admin.md, src/pages/webhooks/use-cases/code-samples/product-update-validation-admin.md, src/pages/webhooks/use-cases/customer-address-modification.md, src/pages/webhooks/use-cases/customer-address-validation.md, src/pages/webhooks/use-cases/discount-code-validation.md, src/pages/webhooks/use-cases/gift-card-validation.md, src/pages/webhooks/use-cases/order-placement-validation.md, src/pages/webhooks/use-cases/product-generate-content.md, src/pages/webhooks/use-cases/product-price-update.md, src/pages/webhooks/use-cases/product-stock-validation.md, src/pages/webhooks/use-cases/product-update-validation.md
This pull request (PR) improves the formatting of the webhooks use cases.
* Changing the heading levels to head4 removes the links in the right nav, which weren't working
* Changing the format of the ACCS configuration section is a better UX and aligns with the webhooks config.
- ...
- ...
=> Improve formating of codeblocks in webhooks use cases

src/pages/app-development/app-submission-guidelines.md, src/pages/starter-kit/checkout/connect.md, src/pages/starter-kit/checkout/index.md
This pull request (PR) updates the app submission guide by,
- Removing duplicated information that exists in several sections.
- Updating some missing "Must-Do" items.
- Clarifying the SaaS vs PaaS differences and linking references.
[CEXT-4720](https://jira.corp.adobe.com/browse/CEXT-4720)
=> CEXT-4720: clarify Must-Do items in app submission guide

src/pages/webhooks/api.md
This pull request (PR) fixes a typo
- ...
- ...
=> Fix typo in heading

src/pages/starter-kit/checkout/configure.md, src/pages/starter-kit/checkout/development.md, src/pages/starter-kit/checkout/index.md, src/pages/starter-kit/checkout/tax-reference.md
Reinforce development guide to help troubleshooting
- Fix a typo in the code of https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/configure/#configure-oauth-server-to-server-credential
- Add app initialization guide in https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/development/
- Add troubleshooting section in https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/development/
=> [Checkout Starter Kit] help development troubleshooting

src/pages/admin-ui-sdk/app-registration.md, src/pages/admin-ui-sdk/configuration.md, src/pages/admin-ui-sdk/index.md
This pull request (PR) updates documentation for code layout best practices and clarify extension support for Admin UI SDK.
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/#admin-ui-sdk-and-adobe-extensions
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/app-registration/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/configuration/#custom-menu-example
- ...
=> [Admin UI SDK] update documentation for code layout best practices and clarify extension support

src/pages/events/custom-event-fields.md
This pull request (PR) adds text that was added in #264, which has been closed due to a lack of CLA.
- ...
- ...
=> Add statement to custom fields topic

src/pages/starter-kit/checkout/connect.md, src/pages/starter-kit/checkout/getting-started.md
This pull request documents in Checkout Starter Kit how to add new ACCS product card.
See https://magento.slack.com/archives/C082J1XJEBC/p1750956146514349
- ...
- ...
=> CEXT-4870: require ACCS product card

src/pages/admin-ui-sdk/app-registration.md, src/pages/admin-ui-sdk/configuration.md
This pull request (PR) update Admin UI SDK documentation based on users feedback
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/app-registration/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/configuration/
- ...
=> Update Admin UI SDK documentation

src/pages/starter-kit/checkout/configure.md, src/pages/starter-kit/checkout/development.md
- Clarify when the eventing configuration is necessary, with a description regarding event registration in app.config.yaml
- Minor improvements in development.md
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/configure/
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/development/
https://jira.corp.adobe.com/browse/CEXT-4921
=> CEXT-4921: clarify event configuration step

src/pages/starter-kit/checkout/connect.md, src/pages/starter-kit/checkout/payment-reference.md
Related https://github.com/adobe/commerce-checkout-starter-kit/pull/45
=> checkout-starter-kit: Fix wrong payment api & commerce integrations precedence

src/pages/events/release-notes.md
This pull request (PR) adds release notes for the eventing modules release.
https://jira.corp.adobe.com/browse/CEXT-5003
=> CEXT-5003: Release eventing modules

src/pages/app-development/app-submission-guidelines.md
This PR updates the app submission guidelines with a required node.js version.
=> node.js version

src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds release notes for Admin UI SDK 3.2.2 release
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/release-notes/
- ...
=> Add release notes for Admin UI SDK 3.2.2
