- package.json
- yarn.lock
This pull request (PR) updates the `gatsby-theme-aio` dependency to the latest version ([`4.9.0`](https://github.com/adobe/aio-theme/releases/tag/@adobe/gatsby-theme-aio@4.9.0)).
**Staging:** _Newly provisioned repo. No production site deployed. Staging build unnecessary._
> COMDOX-596: Update gatsby-theme-aio to 4.9.0

- src/data/navigation/header.js
- src/data/navigation/sections/admin-ui-sdk.js
- src/data/navigation/sections/amazon-sales-channel.js
- src/data/navigation/sections/backoffice.js
- src/data/navigation/sections/index.js
- src/pages/admin-ui-sdk/app-development.md
- src/pages/admin-ui-sdk/configuration.md
- src/pages/admin-ui-sdk/index.md
- src/pages/admin-ui-sdk/installation.md
- src/pages/admin-ui-sdk/reference/menu-app.md
- src/pages/admin-ui-sdk/reference/page-app.md
- src/pages/admin-ui-sdk/release-notes.md
- src/pages/amazon-sales-channel/best-practices/index.md
- src/pages/amazon-sales-channel/index.md
- src/pages/amazon-sales-channel/installation.md
- src/pages/amazon-sales-channel/release-notes.md
- src/pages/backoffice/index.md
This pull request (PR) adds stub files and top/left navigation for Admin UI SDK and Amazon Sales Channel app guides. I'm doing this now to remove barriers for developer contributions.
- ...
- ...
> Add stub files and navigation for SDK and ASC docs

- src/pages/admin-ui-sdk/configuration.md
The published documentation contains a server.js code that has an incorrect URL. This PR corrects this so users can correctly install and work with the Admin UI SDK locally.
- ...
- ...
> CEXT-2057: Fix the server.js URL in the response JSON

- src/pages/admin-ui-sdk/app-registration.md
This pull request (PR) assigns a specific minimum version of the `uix-guest` dependency.
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/app-registration
- ...
> Update dependency version

- src/pages/admin-ui-sdk/installation.md
Fix composer require command due to some missing double commas
- [Install Adobe Commerce Admin UI SDK
](https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/installation/#adobe-commerce-on-cloud-infrastructure)
> Fix composer require backend-uix command

- src/pages/app-development/index.md
This pull request (PR) clarifies the details about frontend development (per request from PMM) to make sure developers know that Spectrum can be used to build apps with the same look and feel of the Admin. 
The original text might be misinterpreted by some to mean that App Builder can be used as the storefront. At present, it cannot.
- https://developer.adobe.com/commerce/extensibility/app-development/#frontend-development
> Clarify frontend development details

- .github/linters/metadata.schema.yml
- .remarkrc.mjs
- package.json
- src/pages/amazon-sales-channel/best-practices/logging-troubleshooting.md
- yarn.lock
This pull request (PR) adds a test for validating metadata (aka "frontmatter") requirements using the [`remark-lint-frontmatter-schema`](https://github.com/JulianCataldo/remark-lint-frontmatter-schema) plugin.
- `title:` (max 60 characters like ExL validation) 
- `description:` (max 160 characters like ExL validation) 
The following metadata enhances **site** search experience by adding corresponding filters to search results:
- `keywords:` (must be one of approved items defined in the schema, which maps to the `feature.yml` file we use in ExL repos) 
The new validation test uses a plugin ([`remark-lint-frontmatter-schema`](https://github.com/JulianCataldo/remark-lint-frontmatter-schema)) for the same package that we're already using to check internal links …
> COMDOX-345: Added validation test for metadata 

- src/pages/webhooks/commands.md
This pull request (PR) creates stubs for each command certain to be in the initial release of Webhooks.
- ...
- ...
> Create stubs for commands

- src/pages/amazon-sales-channel/index.md
This pull request (PR) fixes community engineering slack channel link.
- https://developer.adobe.com/commerce/extensibility/amazon-sales-channel/
> Fix community engineering slack channel link

- src/pages/webhooks/commands.md
This pull request (PR) adds information about `webhooks:dev:run` command
https://jira.corp.adobe.com/browse/CEXT-2387
- ...
- ...
> CEXT-2387: Update webhooks:dev:run command

- src/pages/webhooks/installation.md
This pull request (PR) adds information on how to install ece-tools from git until 2002.1.16 version is released.
- https://developer.adobe.com/commerce/extensibility/webhooks/installation/
- ...
> Instruction on how to install ece-tools from git

- src/pages/webhooks/testing.md
This pull request (PR) fixes inline code formatting that is preventing an internal link from rendering properly.
- https://developer.adobe.com/commerce/extensibility/webhooks/testing/
> Fix .md link syntax

- src/data/navigation/sections/admin-ui-sdk.js
- src/pages/admin-ui-sdk/app-registration.md
- src/pages/admin-ui-sdk/configuration.md
- src/pages/admin-ui-sdk/extension-points/menu.md
- src/pages/admin-ui-sdk/extension-points/order.md
- src/pages/admin-ui-sdk/extension-points/product.md
- src/pages/admin-ui-sdk/release-notes.md
This pull request (PR) adds the documentation for the Admin UI SDK 1.2.0.
- ...
- ...
> Admin SDK UI 1.2.0 docs

- src/pages/webhooks/testing.md
- src/pages/webhooks/xml-schema.md
This pull request (PR) adds information about webhook response caching
- ...
- ...
> CEXT-2403: Caching webhook responses

- .github/workflows/index.yml
This pull request (PR) fixes the indexing workflow [failure](https://github.com/AdobeDocs/commerce-extensibility/actions/runs/6724894582/job/18278143476). Downgrading yarn to v3 in the workflow like in other workflows.
yarn v4 doesn't support node v16.
https://github.com/commerce-docs/commerce-extensibility/actions/runs/6725364432/job/18279583045
Update the indexing workflow in other projects.
> Fix indexing

- src/pages/webhooks/installation.md
Module name in example does not exist. Fixed it.
- https://developer.adobe.com/commerce/extensibility/webhooks/installation/
> Fix wrong module names

- src/pages/webhooks/hooks.md
This pull request (PR) adds information about converting values in hook endpoint responses containing replace operations (replace operation documentation to come in https://jira.corp.adobe.com/browse/CEXT-2484)
- ...
- ...
> CEXT-2455: fromExternalFormat method in converter classes

- src/pages/webhooks/hooks.md
This pull request (PR) adds information about configuring webhooks with array-type fields
https://jira.corp.adobe.com/browse/CEXT-2534
- https://developer.adobe.com/commerce/extensibility/webhooks/hooks/
- ...
> CEXT-2534: Documenting array-type field filtering

- .github/linters/metadata.schema.yml
This pull request (PR) adds the Webhooks keyword  so that it can be used in the frontmatter.
- ...
- ...
> Add Webhooks keyword

- src/pages/amazon-sales-channel/index.md
This pull request (PR) updates the ASC reference app intro to remove a reference to installing the extension. The extension has been removed from Marketplace.
- ...
- ...
> Remove discussion of installing ASC

- src/pages/events/commands.md
This pull request (PR) adds a note about generating fixtures before subscribing events in a performance testing environment. This is an obscure corner case.
Related: https://git.corp.adobe.com/AdobeDocs/commerce-operations.en/pull/731
- ...
- ...
> Add note about generating fixtures

- src/data/navigation/header.js
- src/data/navigation/sections/index.js
- src/data/navigation/sections/starter-kit.js
- src/pages/starter-kit/index.md
This pull request (PR) adds basic navigation for the Starter Kit docs. No content whatsoever.
- ...
- ...
> Add basic navigation

- src/pages/admin-ui-sdk/extension-points/order/view-button.md
This pull request (PR) makes corrections to the order view button parameters.
- ...
- ...
> Correct order view parameters

- src/pages/admin-ui-sdk/extension-points/order/view-button.md
This pull request (PR) removes the class parameter from the order view button extension point.
- ...
- ...
> Remove class from order button

- src/pages/events/configure-commerce.md
- src/pages/events/troubleshooting.md
This pull request (PR) will add documentation on how to resolve stuck deployment on the Cloud due to running in the background eventing consumers.
https://jira.corp.adobe.com/browse/CEXT-2783
- https://developer.adobe.com/commerce/extensibility/events/configure-commerce/
- https://developer.adobe.com/commerce/extensibility/events/troubleshooting/
- ...
> CEXT-2783: Documentation on how to resolve stuck deployment on the Cloud

- src/pages/events/release-notes.md
This pull request (PR) will add information about the new release of commerce eventing
- ...
> CEXT-2784: Release commerce eventing and webhook modules

- src/pages/webhooks/admin-configuration.md
This pull request (PR) adds to the warning on the webhooks admin configuration page about adding new plugin-type webhooks.
- ...
- ...
> Webhooks admin configuration warning addition

- src/pages/index.md
This pull request (PR) moves the OOP section of the front page to be above the in-process page.
- ...
- ...
> Reorder sections on front page

- src/pages/app-development/learning-path.md
This pull request (PR) adds a link for [logging and troubleshooting](https://developer.adobe.com/commerce/extensibility/amazon-sales-channel/best-practices/logging-troubleshooting/) to the [learning path](https://developer.adobe.com/commerce/extensibility/app-development/learning-path/).
> Add logging to learning path

- src/pages/events/commands.md
- src/pages/events/release-notes.md
This pull request (PR) will add release notes for the 1.5.1 release
- [Release notes](https://developer.adobe.com/commerce/extensibility/events/release-notes/)
- ...
> CEXT-2869: Release commerce eventing and commerce eventing service

- src/pages/amazon-sales-channel/best-practices/database-storage.md
This pull request (PR) updates limitations about the Adobe I/O State Library. The [README](https://github.com/adobe/aio-lib-state) for this library was updated last week.
- ...
- ...
> Update Adobe IO State Library details

- src/pages/events/api.md
This pull request (PR) fixes the error with wrong request type for the API endpoint
- ...
> Fit the request method type

- src/pages/webhooks/release-notes.md
This pull request (PR) adds information about 1.3.0 webhooks release
- ...
> CEXT-3055: Release commerce webhooks 1.3.0

- src/_includes/starter-kit-beta.md
- src/data/navigation/sections/starter-kit.js
- src/pages/starter-kit/contact-us.md
- src/pages/starter-kit/create-data-flow.md
- src/pages/starter-kit/customers.md
- src/pages/starter-kit/index.md
- src/pages/starter-kit/launch.md
- src/pages/starter-kit/orders.md
- src/pages/starter-kit/products.md
- src/pages/starter-kit/receive-data.md
- src/pages/starter-kit/shipments.md
- src/pages/starter-kit/stock.md
- src/pages/starter-kit/structure.md
This pull request (PR) adds beta notices to all the files that don't have one. It also adds contact info to the notice
- ...
- ...
> Add missing beta notices

- src/pages/webhooks/hooks.md
- src/pages/webhooks/release-notes.md
This pull request (PR) adds information about 1.3.1 webhooks release
https://jira.corp.adobe.com/browse/CEXT-3067
- https://developer.adobe.com/commerce/extensibility/webhooks/hooks/
- ...
> CEXT-3067: Release commerce webhooks 1.3.1

- src/pages/starter-kit/create-integration.md
This pull request (PR) mentions the info action and requests that it not be disabled or altered.
- ...
- ...
> Add reference to info action

- src/pages/app-development/learning-path.md
- src/pages/webhooks/release-notes.md
This pull request (PR) corrects the date of the webhooks release
- https://developer.adobe.com/commerce/extensibility/webhooks/release-notes/#release-date
- ...
> CEXT-3242: Release the new version of commerce webhooks without admin UI

- src/data/navigation/sections/webhooks.js
- remove a menu link
This pull request (PR) will remove the link from the menu which no longer exists
- https://developer.adobe.com/commerce/extensibility/webhooks/
- ...
> CEXT-3239: Remove webhooks admin UI

- src/pages/events/configure-commerce.md
- src/pages/starter-kit/create-integration.md
This PR updates the Starter Kit instructions for configuring the Eventing setup. Changes were made to the eventing setup documentation in #217 and #218.
@keharper in the future we should revisit this and see if there is a way to integrate these processes, so that future changes to the eventing configuration don't require changes in the starter kit docs.
> Updating eventing instructions in starter kit

- src/pages/events/consume-events.md
Due to some strangeness in GIthub, a suggestion for #219 was not properly committed: see https://github.com/AdobeDocs/commerce-extensibility/pull/219#discussion_r1637093876
> Adding removed section

- src/pages/events/consume-events-examples/runtime-action-commerce-callback.md
- src/pages/events/consume-events.md
This pull request (PR) adds a missing header in the consume events page and fixes some small typos related to docs for consuming events
- https://developer.adobe.com/commerce/extensibility/events/consume-events/
- https://developer.adobe.com/commerce/extensibility/events/consume-events-examples/runtime-action-commerce-callback/
- ...
> CEXT-3214: Fixing missing header and typos

- src/_includes/project-requirements.md
- src/pages/starter-kit/create-integration.md
This pull request (PR) mentions that you must have App Builder access to create a project. Added App Builder to the list of prereqs.
- ...
- ...
> Add App Builder as a prereq

- src/data/navigation/sections/starter-kit.js
This pull request (PR) adds a link in the left navigation to the starter kit tutorials
- ...
- ...
> Add link to Starter Kit tutorials

- src/pages/admin-ui-sdk/configuration.md
This pull request (PR) is to update the configuration page showcasing how to test on a local instance using a project workspace from app builder.
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/configuration/
> Update configuration page to add details on how to test locally pointing to a staging workspace

- src/data/navigation/sections/admin-ui-sdk.js
- src/pages/admin-ui-sdk/app-registration.md
- src/pages/admin-ui-sdk/extension-points/banner-notification.md
- src/pages/admin-ui-sdk/extension-points/customer/grid-columns.md
- src/pages/admin-ui-sdk/extension-points/customer/index.md
- src/pages/admin-ui-sdk/extension-points/customer/mass-action.md
- src/pages/admin-ui-sdk/extension-points/menu.md
- src/pages/admin-ui-sdk/extension-points/order/custom-fees.md
- src/pages/admin-ui-sdk/extension-points/order/index.md
- src/pages/admin-ui-sdk/extension-points/product/index.md
- src/pages/admin-ui-sdk/installation.md
- src/pages/admin-ui-sdk/publish.md
- src/pages/admin-ui-sdk/troubleshooting.md
This pull request (PR) fixes some info in the doc and add missing parts for Admin UI SDK
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/app-registration/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/banner-notification/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/customer/grid-columns/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/customer/mass-action/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/menu/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/extension-points/order/custom-fees/
- https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/publish/
- …
> Fix some info in the doc and add missing parts for Admin UI SDK

- src/data/navigation/sections/app-development.js
- src/pages/app-development/port-extensions.md
This pull request (PR) adjusts the left nav of the App Development Guide
- ...
- ...
> Nav reorg for App Development Guide

- src/pages/admin-ui-sdk/index.md
This pull request (PR) intents to clearly state that switching from an application to an extension will not cause any issues. 
https://developer.adobe.com/commerce/extensibility/admin-ui-sdk/
> Migrating from application to extension and Admin UI SDK compatibility

- src/pages/webhooks/release-notes.md
This pull request (PR) adds release notes for commerce webhooks 1.7.0 release.
https://github.com/AdobeDocs/commerce-extensibility/pull/295
- ...
> CEXT-3976: Release commerce-webhooks 1.7.0

- src/pages/events/api.md
This pull request (PR) adds documentation for the event update and unsubscribe endpoints created in 
https://github.com/magento-commerce/commerce-eventing/pull/148
https://github.com/magento-commerce/commerce-eventing/pull/151
- ...
> CEXT-3974/CEXT-3975: Documentation for event update and unsubscribe endpoints

- src/pages/events/api.md
This pull request (PR) updates the response (added converter for the field) of the GET events subscriptions API call.
https://jira.corp.adobe.com/browse/CEXT-3925
- ...
> CEXT: 3925 Added converter in the response of GET events subscriptions API call.

- src/pages/events/api.md
- src/pages/events/module-development.md
- src/pages/events/release-notes.md
- src/pages/webhooks/release-notes.md
This pull request (PR) adds release notes for the eventing 1.11 and webhooks 1.8 releases.
- https://developer.adobe.com/commerce/extensibility/events/module-development/
- ...
> CEXT-4033: Eventing 1.11 & webhooks 1.8 release notes

- src/pages/webhooks/release-notes.md
This pull request (PR) fixes a typo on the webhooks release notes page that causes an intended comment to be visible.
- ...
> CEXT-4033: Remove visible ticket name from webhooks release notes

- src/pages/starter-kit/checkout/configure.md
- src/pages/starter-kit/checkout/getting-started.md
- src/pages/starter-kit/checkout/reference.md
- src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) adds information on configuring out-of-process shipping methods.
https://jira.corp.adobe.com/browse/CEXT-4103
- https://developer-stage.adobe.com/commerce/extensibility/starter-kit/checkout/use-cases/
- https://developer-stage.adobe.com/commerce/extensibility/starter-kit/checkout/getting-started/
- https://developer-stage.adobe.com/commerce/extensibility/starter-kit/checkout/structure/
- https://developer-stage.adobe.com/commerce/extensibility/starter-kit/checkout/reference/
https://github.com/adobe/commerce-checkout-starter-kit/pull/7
- ...
> CEXT-4103: Document oope-shipping-methods module

- src/data/navigation/sections/checkout-starter-kit.js
- src/data/navigation/sections/integration-starter-kit.js
- src/pages/starter-kit/checkout/index.md
This PR addresses feedback by adding a header to the left nav that indicates which starter kit you are viewing.
I've also added a similar heading for the integration starter kit.
staging: https://developer-stage.adobe.com/commerce/extensibility/starter-kit/checkout/
> checkout starter kit feedback

- src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) adds the example of the request payload for shipping methods extension and additional references to examples of using customer or product attributes data.
https://jira.corp.adobe.com/browse/CEXT-4251
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/use-cases/
https://github.com/adobe/commerce-checkout-starter-kit/pull/10
- ...
> CEXT-4251: Update examples with customer data and product attributes

- src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) adds information that shipping methods can be removed by using oope shipping methods webhook.
https://jira.corp.adobe.com/browse/CEXT-4264
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/ 
- ...
> CEXT-4264: Add the possibility of disabling shipping methods

- src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) adds information of hot to filter out payment methods using webhooks
https://jira.corp.adobe.com/browse/CEXT-4313
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/use-cases/
- ...
> CEXT-4313: Create a new extension to allow filtering payment methods

- src/pages/starter-kit/checkout/getting-started.md
- src/pages/starter-kit/checkout/use-cases.md
This pull request (PR) adds:
-  information about the requirement of having valid credentials in auth.json before installing oope modules. 
-  information about shipping carrier configuration before adding oope shipping methods
https://jira.corp.adobe.com/browse/CEXT-4373
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/getting-started/
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/use-cases/
- ...
> CEXT-4373: Update the oope shipping methods documentation

- .remarkrc.mjs
This pull request (PR) adds `https://developer.adobe.com/developer-console/*` to the `skipUrlPatterns` section of the `.remarkrc.mjs` file. Skipping this domain allows to avoid failures of the link checking test related to the temporary bug on the website until it's fixed.
- ...
- ...
> Add domain to skipUrlPatterns

- src/pages/admin-ui-sdk/release-notes.md
- src/pages/events/commands.md
This pull request (PR) adds a link to the Admin UI SDK release notes and fixes a typo.
- ...
- ...
> Fix typo, add link

- src/pages/starter-kit/checkout/connect.md
- src/pages/starter-kit/checkout/getting-started.md
- src/pages/starter-kit/checkout/use-cases.md
- src/pages/starter-kit/integration/create-integration.md
This PR adds badging for the starter kits based on the strategy added by #352.
It appears that having the tags at the beginning a line causes the parser to interpret everything else in the line as `html` and not `markdown`. I attempted to shadow the parser and modify it to resolve the issue, but I was unsuccessful. My simple, but inelegant, solution is to add a no-width space character (`&#8203;`) to the beginning of the line. I also tried incorporating this character into the shadowed component, but that did not modify the offending parser behavior.
> Badging for starter kits

- src/pages/events/api.md
- src/pages/events/release-notes.md
This pull request (PR) adds release notes for commerce eventing 1.12.1 release
https://jira.corp.adobe.com/browse/CEXT-4580
- ...
> CEXT-4580: Release commerce eventing 1.12.1

- src/pages/starter-kit/checkout/payment-use-cases.md
- src/pages/starter-kit/checkout/shipping-use-cases.md
- src/pages/starter-kit/checkout/tax-use-cases.md
- Added PaaS webhook guide for validate-payment
- Fixed typos in ACCS webhook fields of validate-payments (missing `data`)
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/use-cases/#validate-payment-info
> CEXT-4634: Add PaaS webhook guide for validate-payment

- src/pages/starter-kit/checkout/payment-reference.md
- src/pages/starter-kit/checkout/payment-usage.md
This pull request (PR) 
- ...
- ...
> CEXT-4672: document update behaviour of `POST /V1/oope_payment_method`

- src/pages/webhooks/hooks.md
This pull request (PR) adds examples of how to use contexts to retrieve additional data for the webhook payload.
- https://developer.adobe.com/commerce/extensibility/webhooks/hooks/
- ...
> CEXT-4676: Update the documentation with webhook context section

- src/pages/starter-kit/checkout/shipping-use-cases.md
This pull request (PR) adds an example of the selected shipping methods in the webhook payload
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/shipping-use-cases/
- ...
> CEXT-4693: Extend the shipping methods webhook payload with the selected method

- src/_includes/checkout-version.md
- src/pages/starter-kit/checkout/getting-started.md
- src/pages/starter-kit/checkout/payment-install.md
- src/pages/starter-kit/checkout/shipping-install.md
- src/pages/starter-kit/checkout/tax-install.md
- Update the minimum Commerce version of Tax to v2.4.6
- While evaluating the effort to support v2.4.5 for taxes, declare the minimum Commerce/PHP versions for each OOPE module explicitly.
@jhadobe Please feel free to update this PR as you prefer. Thanks!
https://jira.corp.adobe.com/browse/CEXT-4724
> CEXT-4724: Update the minimum Commerce version of Tax to v2.4.6

- src/_includes/webhook-auth.md
- src/data/navigation/sections/app-development.js
- src/pages/app-development/app-submission-guidelines.md
This PR creates a new page that outlines the requirements and best practices for app builder submission for Commerce apps.
Staging link: https://adobedocs.github.io/commerce-extensibility/app-development/app-submission-guidelines/
> App builder submission guidelines

- src/pages/webhooks/api.md
- src/pages/webhooks/create-webhooks.md
This pull request (PR) adds info about using REST on ACCS webhooks to the extensibility repo.
- ...
- ...
> Move webhook REST endpoints from services repo

- src/pages/app-development/app-submission-guidelines.md
This pull request (PR) adds alternative options for app submission review/testing based on internal feedback.
https://developer.adobe.com/commerce/extensibility/app-development/app-submission-guidelines/#runtime-and-testing
whatsnew
Added [alternative options](https://developer.adobe.com/commerce/extensibility/app-development/app-submission-guidelines/#runtime-and-testing) for app submission review/testing.
> Alternative testing options for app submission

- src/_includes/conditional-event-example.md
- src/_includes/conditional-event.md
- src/_includes/nested-event.md
- src/_includes/sample-event.md
- src/data/navigation/sections/events.js
- src/pages/events/api.md
- src/pages/events/commands.md
- src/pages/events/conditional-events.md
- src/pages/events/configure-additional-event-providers.md
- src/pages/events/configure-commerce.md
- src/pages/events/convert-field-values.md
- src/pages/events/create-events.md
- src/pages/events/custom-event-fields.md
- src/pages/events/installation.md
- src/pages/events/module-development.md
This pull request (PR) adds badging for Eventing. I was able to keep SaaS and PaaS discussions in separate topics for the most part, because event definitions are much simpler than in webhooks. I converted several passages to include files.
Staging build: https://adobedocs.github.io/commerce-extensibility/events/
- ...
- ...
> Add badging for eventing

- src/data/navigation/sections/app-development.js
- src/pages/app-development/app-submission-guidelines.md
- src/pages/app-development/extension-compatibility.md
This PR adds a guide to App Builder extension compatibility.
Staging: https://developer-stage.adobe.com/commerce/extensibility/app-development/extension-compatibility/
> Cext 4818 app builder compatibility

- src/data/navigation/sections/webhooks.js
This pull request (PR) removes a TOC entry in the webhooks guide that 404s.
> fix: 404 in webhooks TOC

- src/pages/starter-kit/checkout/configure.md
- src/pages/starter-kit/checkout/getting-started.md
…tarter kit
Updated doc to add multi event provider support in checkout starter kit
https://github.com/adobe/commerce-checkout-starter-kit/pull/46
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/getting-started/
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/configure/#configure-eventing
- ...
> CEXT-4871: Updated doc for multi-event provider support in Checkout Starter Kit

- src/pages/starter-kit/integration/webhooks.md
- src/pages/webhooks/use-cases/product-price-update.md
- src/pages/webhooks/use-cases/product-stock-validation.md
- src/pages/webhooks/use-cases/product-update-validation.md
In conjunction with https://github.com/AdobeDocs/commerce-webapi/pull/488/files, this PR removes spaces from SKUs in example code, since they are causing issues in the integration starter kit.
> remove spaces from skus

- src/pages/starter-kit/checkout/eds.md
This pull request (PR) fixes a broken link to the experience league checkout drop-in page.
- The current link points to https://experienceleague.adobe.com/developer/commerce/storefront/drop-ins/checkout/
- It should point to https://experienceleague.adobe.com/developer/commerce/storefront/dropins/checkout/
- https://developer.adobe.com/commerce/extensibility/starter-kit/checkout/eds/
N/A
> Fix broken link to experience league checkout drop-in page

- src/pages/app-development/app-builder-partnership-essentials.md
This pull request (PR) fixes some links in the [partner essentials](https://developer.adobe.com/commerce/extensibility/app-development/app-builder-partnership-essentials/) topic as requested by PgM.
https://developer.adobe.com/commerce/extensibility/app-development/app-builder-partnership-essentials/
> fix: links in partner essentials topic
